### ISSUE TITLE
Add alpha codes to species_table

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/name_conversions#1]
It would be helpful to have alpha codes added to the species table.

**Comment by sammlapp** [comment]
I've added two tables from [Goldeneye](https://github.com/rhine3/goldeneye/blob/master/src/ibp-alpha-codes_2021.csv) for IBP and BBL alpha codes, and helper functions. We now have these functions: 
```
 'alpha_to_common',
 'alpha_to_sci',
 'bn_common_to_sci',
 'common_to_alpha',
 'common_to_sci',
 'sci_to_alpha',
 'sci_to_bn_common',
 'sci_to_xc_common',
 'xc_common_to_sci'
 'get_species_list',
```
